LANGUAGES = {
    'zh_CN': {
        'window_title': 'Zoffline-CN-Tool',
        'process_status': '进程状态:',
        'launcher_status': 'ZwiftLauncher:',
        'app_status': 'ZwiftApp:',
        'caddy_status': 'Caddy:',
        'zoffline_status': 'Zoffline_local:',
        'server_settings': '服务器设置:',
        'ip_label': 'IP:',
        'save_ip': '保存IP',
        'main_functions': '主要功能',
        'launch_community': '一键启动社区服Zwift',
        'launch_official': '一键启动官服Zwift',
        'update_resources': '更新下载资源文件(手动)',
        'advanced_options': '高级选项',
        'select_cert': '手动选择证书',
        'import_host': '导入Host设置',
        'import_sys_cert': '自动导入系统证书',
        'import_client_cert': '自动导入客户端证书',
        'start_caddy': '启动Caddy后台',
        'check_official_ver': '查询官服版本',
        'check_community_ver': '查询社区服版本',
        'check_local_ver': '查询内置版本库',
        'force_update': '强制"更新"版本',
        'check_proxy': '检查系统代理',
        'check_ports': '检查端口占用',
        'kill_ports': '强行终止端口占用',
        'test_remote': '远程端口测试',
        'test_local': '本地host和caddy测试',
        'test_https': '社区服HTTPS测试',
        'test_connectivity': '一键测试连通性',
        'exit': '退出',
        'kill_all': '终止所有进程',
        'clean_network': '清除网络配置',
        'add_server': '添加服务器',
        'test_servers': '测试服务器',
        'server_error': '服务器错误',
        'server_timeout': '连接超时',
        'server_exists': '服务器已存在',
        'server_invalid': '无效的服务器地址',
        'server_delete_error': '无法删除本地服务器',
        'server_note': '编辑备注',
        'server_note_title': '编辑服务器备注',
        'server_add_success': '服务器添加成功',
        'server_add_error': '添加服务器失败',
        'server_delete_success': '服务器删除成功',
        'server_test_success': '服务器测试完成',
        'server_test_error': '服务器测试失败',
        'current_server': '当前服务器:',
        'manage_servers': '管理服务器',
        'close': '关闭',
        'server_list_title': '服务器列表',
        'server_list_empty': '没有可用的服务器',
        'server_selected': '已选择服务器: {}',
        'server_select_error': '选择服务器失败',
        # 菜单项
        'menu_file': '文件(&F)',
        'menu_save_config': '保存配置',
        'menu_reload_config': '重新加载配置',
        'menu_exit': '退出',
        'menu_tools': '工具(&T)',
        'menu_version': '版本(&V)',
        'menu_test': '测试(&D)',
        'menu_help': '帮助(&H)',
        'menu_about': '关于',
        'menu_usage': '使用说明',
    },
    'en_US': {
        'window_title': 'Zoffline-CN-Tool',
        'process_status': 'Process Status:',
        'launcher_status': 'ZwiftLauncher:',
        'app_status': 'ZwiftApp:',
        'caddy_status': 'Caddy:',
        'zoffline_status': 'Zoffline_local:',
        'server_settings': 'Server Settings:',
        'ip_label': 'IP:',
        'save_ip': 'Save IP',
        'main_functions': 'Main Functions',
        'launch_community': 'Launch Community Zwift',
        'launch_official': 'Launch Official Zwift',
        'update_resources': 'Update Resources (Manual)',
        'advanced_options': 'Advanced Options',
        'select_cert': 'Select Certificate',
        'import_host': 'Import Host Settings',
        'import_sys_cert': 'Import System Certificate',
        'import_client_cert': 'Import Client Certificate',
        'start_caddy': 'Start Caddy Backend',
        'check_official_ver': 'Check Official Version',
        'check_community_ver': 'Check Community Version',
        'check_local_ver': 'Check Local Version',
        'force_update': 'Force Update Version',
        'check_proxy': 'Check System Proxy',
        'check_ports': 'Check Port Usage',
        'kill_ports': 'Force Kill Port Usage',
        'test_remote': 'Test Remote Port',
        'test_local': 'Test Local Host and Caddy',
        'test_https': 'Test Community HTTPS',
        'test_connectivity': 'Test All Connectivity',
        'exit': 'Exit',
        'kill_all': 'Kill All Processes',
        'clean_network': 'Clean Network Config',
        'add_server': 'Add Server',
        'test_servers': 'Test Servers',
        'server_error': 'Server Error',
        'server_timeout': 'Connection Timeout',
        'server_exists': 'Server Already Exists',
        'server_invalid': 'Invalid Server Address',
        'server_delete_error': 'Cannot Delete Local Server',
        'server_note': 'Edit Note',
        'server_note_title': 'Edit Server Note',
        'server_add_success': 'Server Added Successfully',
        'server_add_error': 'Failed to Add Server',
        'server_delete_success': 'Server Deleted Successfully',
        'server_test_success': 'Server Test Complete',
        'server_test_error': 'Server Test Failed',
        'current_server': 'Current Server:',
        'manage_servers': 'Manage Servers',
        'close': 'Close',
        'server_list_title': 'Server List',
        'server_list_empty': 'No Servers Available',
        'server_selected': 'Selected Server: {}',
        'server_select_error': 'Failed to Select Server',
        # Menu items
        'menu_file': 'File(&F)',
        'menu_save_config': 'Save Config',
        'menu_reload_config': 'Reload Config',
        'menu_exit': 'Exit',
        'menu_tools': 'Tools(&T)',
        'menu_version': 'Version(&V)',
        'menu_test': 'Test(&D)',
        'menu_help': 'Help(&H)',
        'menu_about': 'About',
        'menu_usage': 'Usage Guide',
    }
} 