name: pyinstaller

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - uses: engineerd/configurator@v0.0.10
      with:
        name: "upx.exe"
        url: "https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win64.zip"
        pathInArchive: "upx-4.2.2-win64/upx.exe"

    - name: Download and extract caddy.exe
      run: |
        curl -L -o caddy.zip https://github.com/caddyserver/caddy/releases/download/v2.9.1/caddy_2.9.1_windows_amd64.zip
        powershell -Command "Expand-Archive -Path caddy.zip -DestinationPath . -Force"
        if (Test-Path -Path ".\caddy.exe") {
            Write-Host "caddy.exe Downloaded"
        } else {
            Write-Host "[Error] caddy.exe Not Found"
            exit 1
        }

    - run: pip install -r requirements.txt
    - run: pip install pyinstaller
    - run: pyinstaller Zoffline-CN-Tool.spec

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
